// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: world/user.proto

package world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ユーザ(カメラ)の位置情報
type Transform_ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Transform_) Reset() {
	*x = Transform_{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transform_) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform_) ProtoMessage() {}

func (x *Transform_) ProtoReflect() protoreflect.Message {
	mi := &file_world_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform_.ProtoReflect.Descriptor instead.
func (*Transform_) Descriptor() ([]byte, []int) {
	return file_world_user_proto_rawDescGZIP(), []int{0}
}

func (x *Transform_) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Transform_) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Transform_) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// ユーザ(カメラ)の回転情報
type Rotation_ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EulerX float32 `protobuf:"fixed32,1,opt,name=eulerX,proto3" json:"eulerX,omitempty"`
	EulerY float32 `protobuf:"fixed32,2,opt,name=eulerY,proto3" json:"eulerY,omitempty"`
	EulerZ float32 `protobuf:"fixed32,3,opt,name=eulerZ,proto3" json:"eulerZ,omitempty"`
}

func (x *Rotation_) Reset() {
	*x = Rotation_{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rotation_) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rotation_) ProtoMessage() {}

func (x *Rotation_) ProtoReflect() protoreflect.Message {
	mi := &file_world_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rotation_.ProtoReflect.Descriptor instead.
func (*Rotation_) Descriptor() ([]byte, []int) {
	return file_world_user_proto_rawDescGZIP(), []int{1}
}

func (x *Rotation_) GetEulerX() float32 {
	if x != nil {
		return x.EulerX
	}
	return 0
}

func (x *Rotation_) GetEulerY() float32 {
	if x != nil {
		return x.EulerY
	}
	return 0
}

func (x *Rotation_) GetEulerZ() float32 {
	if x != nil {
		return x.EulerZ
	}
	return 0
}

// ユーザの情報
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// room.proto 内の Join RPC を使用した際に返却される user_id が設定される
	UserId    string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Transform *Transform_ `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	Rotation  *Rotation_  `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_world_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_world_user_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetTransform() *Transform_ {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *User) GetRotation() *Rotation_ {
	if x != nil {
		return x.Rotation
	}
	return nil
}

var File_world_user_proto protoreflect.FileDescriptor

var file_world_user_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x36, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x7a, 0x22, 0x53, 0x0a, 0x09, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x75, 0x6c, 0x65, 0x72, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x65, 0x75, 0x6c, 0x65, 0x72, 0x58, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x75, 0x6c, 0x65, 0x72, 0x59,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x65, 0x75, 0x6c, 0x65, 0x72, 0x59, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x75, 0x6c, 0x65, 0x72, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x65, 0x75, 0x6c, 0x65, 0x72, 0x5a, 0x22, 0x7e, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x2c, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x75, 0x2d, 0x74, 0x6f, 0x75, 0x2f, 0x72, 0x65, 0x61,
	0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_world_user_proto_rawDescOnce sync.Once
	file_world_user_proto_rawDescData = file_world_user_proto_rawDesc
)

func file_world_user_proto_rawDescGZIP() []byte {
	file_world_user_proto_rawDescOnce.Do(func() {
		file_world_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_world_user_proto_rawDescData)
	})
	return file_world_user_proto_rawDescData
}

var file_world_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_world_user_proto_goTypes = []interface{}{
	(*Transform_)(nil), // 0: world.Transform_
	(*Rotation_)(nil),  // 1: world.Rotation_
	(*User)(nil),       // 2: world.User
}
var file_world_user_proto_depIdxs = []int32{
	0, // 0: world.User.transform:type_name -> world.Transform_
	1, // 1: world.User.rotation:type_name -> world.Rotation_
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_world_user_proto_init() }
func file_world_user_proto_init() {
	if File_world_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_world_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transform_); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rotation_); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_world_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_user_proto_goTypes,
		DependencyIndexes: file_world_user_proto_depIdxs,
		MessageInfos:      file_world_user_proto_msgTypes,
	}.Build()
	File_world_user_proto = out.File
	file_world_user_proto_rawDesc = nil
	file_world_user_proto_goTypes = nil
	file_world_user_proto_depIdxs = nil
}
